package com.liderbs.modelo;
// Generated 26-abr-2017 15:46:42 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Academiclevel generated by hbm2java
 */
public class Academiclevel  implements java.io.Serializable {


     private Integer idacademiclevel;
     private String name;
     private Set<Trainer> trainers = new HashSet<Trainer>(0);

    public Academiclevel() {
    }

    public Academiclevel(String name, Set<Trainer> trainers) {
       this.name = name;
       this.trainers = trainers;
    }
   
    public Integer getIdacademiclevel() {
        return this.idacademiclevel;
    }
    
    public void setIdacademiclevel(Integer idacademiclevel) {
        this.idacademiclevel = idacademiclevel;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Trainer> getTrainers() {
        return this.trainers;
    }
    
    public void setTrainers(Set<Trainer> trainers) {
        this.trainers = trainers;
    }




}


