package com.liderbs.modelo;
// Generated 02-abr-2017 11:42:14 by Hibernate Tools 4.0.0



/**
 * AccountType generated by hbm2java
 */
public class AccountType  implements java.io.Serializable {


     private Integer idaccountType;
     private String accountTypeName;
     private String accountTypeDescription;

    public AccountType() {
    }

    public AccountType(String accountTypeName, String accountTypeDescription) {
       this.accountTypeName = accountTypeName;
       this.accountTypeDescription = accountTypeDescription;
    }
   
    public Integer getIdaccountType() {
        return this.idaccountType;
    }
    
    public void setIdaccountType(Integer idaccountType) {
        this.idaccountType = idaccountType;
    }
    public String getAccountTypeName() {
        return this.accountTypeName;
    }
    
    public void setAccountTypeName(String accountTypeName) {
        this.accountTypeName = accountTypeName;
    }
    public String getAccountTypeDescription() {
        return this.accountTypeDescription;
    }
    
    public void setAccountTypeDescription(String accountTypeDescription) {
        this.accountTypeDescription = accountTypeDescription;
    }




}


