package com.liderbs.modelo;
// Generated 07-abr-2017 11:54:12 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idAccount;
     private Profile profile;
     private String accountName;
     private String accountDescription;
     private Date accountCreated;
     private Integer accountStatus;
     private String accountUserCreated;
     private Integer accountDefault;
     private Set<Users> userses = new HashSet<Users>(0);

    public Account() {
    }

	
    public Account(Profile profile) {
        this.profile = profile;
    }
    public Account(Profile profile, String accountName, String accountDescription, Date accountCreated, Integer accountStatus, String accountUserCreated, Integer accountDefault, Set<Users> userses) {
       this.profile = profile;
       this.accountName = accountName;
       this.accountDescription = accountDescription;
       this.accountCreated = accountCreated;
       this.accountStatus = accountStatus;
       this.accountUserCreated = accountUserCreated;
       this.accountDefault = accountDefault;
       this.userses = userses;
    }
   
    public Integer getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(Integer idAccount) {
        this.idAccount = idAccount;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    public String getAccountDescription() {
        return this.accountDescription;
    }
    
    public void setAccountDescription(String accountDescription) {
        this.accountDescription = accountDescription;
    }
    public Date getAccountCreated() {
        return this.accountCreated;
    }
    
    public void setAccountCreated(Date accountCreated) {
        this.accountCreated = accountCreated;
    }
    public Integer getAccountStatus() {
        return this.accountStatus;
    }
    
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }
    public String getAccountUserCreated() {
        return this.accountUserCreated;
    }
    
    public void setAccountUserCreated(String accountUserCreated) {
        this.accountUserCreated = accountUserCreated;
    }
    public Integer getAccountDefault() {
        return this.accountDefault;
    }
    
    public void setAccountDefault(Integer accountDefault) {
        this.accountDefault = accountDefault;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


