package com.liderbs.modelo;
// Generated 14-abr-2017 19:41:32 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Autorizationtype generated by hbm2java
 */
public class Autorizationtype  implements java.io.Serializable {


     private Integer idAutorizationtype;
     private String autorizationtypeName;
     private Set<Autorization> autorizations = new HashSet<Autorization>(0);

    public Autorizationtype() {
    }

    public Autorizationtype(String autorizationtypeName, Set<Autorization> autorizations) {
       this.autorizationtypeName = autorizationtypeName;
       this.autorizations = autorizations;
    }
   
    public Integer getIdAutorizationtype() {
        return this.idAutorizationtype;
    }
    
    public void setIdAutorizationtype(Integer idAutorizationtype) {
        this.idAutorizationtype = idAutorizationtype;
    }
    public String getAutorizationtypeName() {
        return this.autorizationtypeName;
    }
    
    public void setAutorizationtypeName(String autorizationtypeName) {
        this.autorizationtypeName = autorizationtypeName;
    }
    public Set<Autorization> getAutorizations() {
        return this.autorizations;
    }
    
    public void setAutorizations(Set<Autorization> autorizations) {
        this.autorizations = autorizations;
    }




}


