package com.liderbs.modelo;
// Generated 17-may-2017 14:50:38 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer idcategory;
     private Level level;
     private String description;
     private Set<Users> userses = new HashSet<Users>(0);

    public Category() {
    }

	
    public Category(Level level) {
        this.level = level;
    }
    public Category(Level level, String description, Set<Users> userses) {
       this.level = level;
       this.description = description;
       this.userses = userses;
    }
   
    public Integer getIdcategory() {
        return this.idcategory;
    }
    
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }
    public Level getLevel() {
        return this.level;
    }
    
    public void setLevel(Level level) {
        this.level = level;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


