package com.liderbs.modelo;
// Generated 04-sep-2017 15:26:20 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private Integer idcities;
     private String citiesName;
     private Set<Users> userses = new HashSet<Users>(0);

    public Cities() {
    }

    public Cities(String citiesName, Set<Users> userses) {
       this.citiesName = citiesName;
       this.userses = userses;
    }
   
    public Integer getIdcities() {
        return this.idcities;
    }
    
    public void setIdcities(Integer idcities) {
        this.idcities = idcities;
    }
    public String getCitiesName() {
        return this.citiesName;
    }
    
    public void setCitiesName(String citiesName) {
        this.citiesName = citiesName;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


