package com.liderbs.modelo;
// Generated 10-oct-2017 14:25:00 by Hibernate Tools 4.0.0


import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * ConsumptionDetail generated by hbm2java
 */
public class ConsumptionDetail  implements java.io.Serializable {

	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idconsumptionDetail;
     private Integer idconsumption;
     private Date fecha;
     private Date hora;
     private Integer cantidad;
     private Integer idusuarioCreo;
     private String usuarioCreo;

    public ConsumptionDetail() {
    }

    public ConsumptionDetail(Integer idconsumption, Date fecha, Date hora, Integer cantidad, Integer idusuarioCreo, String usuarioCreo) {
       this.idconsumption = idconsumption;
       this.fecha = fecha;
       this.hora = hora;
       this.cantidad = cantidad;
       this.idusuarioCreo = idusuarioCreo;
       this.usuarioCreo = usuarioCreo;
    }
   
    public Integer getIdconsumptionDetail() {
        return this.idconsumptionDetail;
    }
    
    public void setIdconsumptionDetail(Integer idconsumptionDetail) {
        this.idconsumptionDetail = idconsumptionDetail;
    }
    public Integer getIdconsumption() {
        return this.idconsumption;
    }
    
    public void setIdconsumption(Integer idconsumption) {
        this.idconsumption = idconsumption;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getIdusuarioCreo() {
        return this.idusuarioCreo;
    }
    
    public void setIdusuarioCreo(Integer idusuarioCreo) {
        this.idusuarioCreo = idusuarioCreo;
    }
    public String getUsuarioCreo() {
        return this.usuarioCreo;
    }
    
    public void setUsuarioCreo(String usuarioCreo) {
        this.usuarioCreo = usuarioCreo;
    }




}


