package com.liderbs.modelo;
// Generated 10-oct-2017 14:25:00 by Hibernate Tools 4.0.0


import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Consumption generated by hbm2java
 */
public class Consumption  implements java.io.Serializable {

	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idconsumption;
     private Integer idreservation;
     private Date fecha;
     private String usuariodocumento;
     private String usuarionombre;
     private String reservation;
     private Integer placeId;
     private String placeName;
     private Integer cantidad;
     private Integer consumido;

    public Consumption() {
    }

    public Consumption(Integer idreservation, Date fecha, String usuariodocumento, String usuarionombre, String reservation, Integer placeId, String placeName, Integer cantidad, Integer consumido) {
       this.idreservation = idreservation;
       this.fecha = fecha;
       this.usuariodocumento = usuariodocumento;
       this.usuarionombre = usuarionombre;
       this.reservation = reservation;
       this.placeId = placeId;
       this.placeName = placeName;
       this.cantidad = cantidad;
       this.consumido = consumido;
    }
   
    public Integer getIdconsumption() {
        return this.idconsumption;
    }
    
    public void setIdconsumption(Integer idconsumption) {
        this.idconsumption = idconsumption;
    }
    public Integer getIdreservation() {
        return this.idreservation;
    }
    
    public void setIdreservation(Integer idreservation) {
        this.idreservation = idreservation;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getUsuariodocumento() {
        return this.usuariodocumento;
    }
    
    public void setUsuariodocumento(String usuariodocumento) {
        this.usuariodocumento = usuariodocumento;
    }
    public String getUsuarionombre() {
        return this.usuarionombre;
    }
    
    public void setUsuarionombre(String usuarionombre) {
        this.usuarionombre = usuarionombre;
    }
    public String getReservation() {
        return this.reservation;
    }
    
    public void setReservation(String reservation) {
        this.reservation = reservation;
    }
    public Integer getPlaceId() {
        return this.placeId;
    }
    
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }
    public String getPlaceName() {
        return this.placeName;
    }
    
    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getConsumido() {
        return this.consumido;
    }
    
    public void setConsumido(Integer consumido) {
        this.consumido = consumido;
    }




}


