package com.liderbs.modelo;
// Generated 26-abr-2017 15:46:42 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {

	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idcourses;
     private String name;
     private String description;
     private String certificator;
     private Date datecertified;
     private Set<Trainer> trainers = new HashSet<Trainer>(0);

    public Courses() {
    }

    public Courses(String name, String description, String certificator, Date datecertified, Set<Trainer> trainers) {
       this.name = name;
       this.description = description;
       this.certificator = certificator;
       this.datecertified = datecertified;
       this.trainers = trainers;
    }
   
    public Integer getIdcourses() {
        return this.idcourses;
    }
    
    public void setIdcourses(Integer idcourses) {
        this.idcourses = idcourses;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCertificator() {
        return this.certificator;
    }
    
    public void setCertificator(String certificator) {
        this.certificator = certificator;
    }
    public Date getDatecertified() {
        return this.datecertified;
    }
    
    public void setDatecertified(Date datecertified) {
        this.datecertified = datecertified;
    }
    public Set<Trainer> getTrainers() {
        return this.trainers;
    }
    
    public void setTrainers(Set<Trainer> trainers) {
        this.trainers = trainers;
    }




}


