package com.liderbs.modelo;
// Generated 26-abr-2017 15:46:42 by Hibernate Tools 4.0.0



/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private EstadoId id;
     private Pais pais;
     private String estadonombre;

    public Estado() {
    }

	
    public Estado(EstadoId id, Pais pais) {
        this.id = id;
        this.pais = pais;
    }
    public Estado(EstadoId id, Pais pais, String estadonombre) {
       this.id = id;
       this.pais = pais;
       this.estadonombre = estadonombre;
    }
   
    public EstadoId getId() {
        return this.id;
    }
    
    public void setId(EstadoId id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getEstadonombre() {
        return this.estadonombre;
    }
    
    public void setEstadonombre(String estadonombre) {
        this.estadonombre = estadonombre;
    }




}


