package com.liderbs.modelo;
// Generated 08-jun-2017 9:28:28 by Hibernate Tools 4.0.0



/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer idestado;
     private Pais pais;
     private String estadonombre;

    public Estado() {
    }

	
    public Estado(Pais pais) {
        this.pais = pais;
    }
    public Estado(Pais pais, String estadonombre) {
       this.pais = pais;
       this.estadonombre = estadonombre;
    }
   
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getEstadonombre() {
        return this.estadonombre;
    }
    
    public void setEstadonombre(String estadonombre) {
        this.estadonombre = estadonombre;
    }




}


