package com.liderbs.modelo;
// Generated 26-abr-2017 15:46:42 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Experience generated by hbm2java
 */
public class Experience  implements java.io.Serializable {

	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idexperience;
     private Job job;
     private String company;
     private Integer country;
     private Integer region;
     private String city;
     private Date startdate;
     private Date enddate;
     private String function;
     private Set<Trainer> trainers = new HashSet<Trainer>(0);

    public Experience() {
    }

	
    public Experience(Job job) {
        this.job = job;
    }
    public Experience(Job job, String company, Integer country, Integer region, String city, Date startdate, Date enddate, String function, Set<Trainer> trainers) {
       this.job = job;
       this.company = company;
       this.country = country;
       this.region = region;
       this.city = city;
       this.startdate = startdate;
       this.enddate = enddate;
       this.function = function;
       this.trainers = trainers;
    }
   
    public Integer getIdexperience() {
        return this.idexperience;
    }
    
    public void setIdexperience(Integer idexperience) {
        this.idexperience = idexperience;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public Integer getCountry() {
        return this.country;
    }
    
    public void setCountry(Integer country) {
        this.country = country;
    }
    public Integer getRegion() {
        return this.region;
    }
    
    public void setRegion(Integer region) {
        this.region = region;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public String getFunction() {
        return this.function;
    }
    
    public void setFunction(String function) {
        this.function = function;
    }
    public Set<Trainer> getTrainers() {
        return this.trainers;
    }
    
    public void setTrainers(Set<Trainer> trainers) {
        this.trainers = trainers;
    }




}


