package com.liderbs.modelo;
// Generated 26-abr-2017 15:46:42 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Identification generated by hbm2java
 */
public class Identification  implements java.io.Serializable {


     private Integer ididentification;
     private String name;
     private Set<Trainer> trainers = new HashSet<Trainer>(0);

    public Identification() {
    }

    public Identification(String name, Set<Trainer> trainers) {
       this.name = name;
       this.trainers = trainers;
    }
   
    public Integer getIdidentification() {
        return this.ididentification;
    }
    
    public void setIdidentification(Integer ididentification) {
        this.ididentification = ididentification;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Trainer> getTrainers() {
        return this.trainers;
    }
    
    public void setTrainers(Set<Trainer> trainers) {
        this.trainers = trainers;
    }




}


