package com.liderbs.modelo;
// Generated 07-abr-2017 10:59:26 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idMenu;
     private String description;
     private String caption;
     private String path;
     private String icon;
     private Set<Options> optionses = new HashSet<Options>(0);

    public Menu() {
    }

    public Menu(String description, String caption, String path, String icon, Set<Options> optionses) {
       this.description = description;
       this.caption = caption;
       this.path = path;
       this.icon = icon;
       this.optionses = optionses;
    }
   
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Set<Options> getOptionses() {
        return this.optionses;
    }
    
    public void setOptionses(Set<Options> optionses) {
        this.optionses = optionses;
    }




}


