package com.liderbs.modelo;
// Generated 05-abr-2017 21:53:29 by Hibernate Tools 4.0.0



/**
 * MenuHasOptions generated by hbm2java
 */
public class MenuHasOptions  implements java.io.Serializable {


     private Long id;
     private Menu menu;

    public MenuHasOptions() {
    }

    public MenuHasOptions(Long id, Menu menu) {
       this.id = id;
       this.menu = menu;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }




}


