package com.liderbs.modelo;
// Generated 05-abr-2017 21:53:29 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer idMenu;
     private String description;
     private String caption;
     private String path;
     private String icon;
     private Set<MenuHasOptions> menuHasOptionses = new HashSet<MenuHasOptions>(0);

    public Menu() {
    }

    public Menu(String description, String caption, String path, String icon, Set<MenuHasOptions> menuHasOptionses) {
       this.description = description;
       this.caption = caption;
       this.path = path;
       this.icon = icon;
       this.menuHasOptionses = menuHasOptionses;
    }
   
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Set<MenuHasOptions> getMenuHasOptionses() {
        return this.menuHasOptionses;
    }
    
    public void setMenuHasOptionses(Set<MenuHasOptions> menuHasOptionses) {
        this.menuHasOptionses = menuHasOptionses;
    }




}


