package com.liderbs.modelo;
// Generated 26-abr-2017 15:46:42 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idpais;
     private String paisnombre;
     private Set<Estado> estados = new HashSet<Estado>(0);

    public Pais() {
    }

    public Pais(String paisnombre, Set<Estado> estados) {
       this.paisnombre = paisnombre;
       this.estados = estados;
    }
   
    public Integer getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(Integer idpais) {
        this.idpais = idpais;
    }
    public String getPaisnombre() {
        return this.paisnombre;
    }
    
    public void setPaisnombre(String paisnombre) {
        this.paisnombre = paisnombre;
    }
    public Set<Estado> getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set<Estado> estados) {
        this.estados = estados;
    }




}


