package com.liderbs.modelo;
// Generated 14-abr-2017 19:41:32 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Place generated by hbm2java
 */
public class Place  implements java.io.Serializable {


	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idPlace;
     private String placeName;
     private String placeAddress;
     private String placePhone;
     private String placePhoneAlt;
     private Date placeCreated;
     private Integer placeStatus;
     private Integer placeOwner;
     private Integer placeIsVzone;
     private Integer accountID;
     private String fiscalID;
     private Integer country;
     private Integer province;
     private String city;
     private String owner_name;
     private String facebook;
     private String instagram;
     private String website;
     private Date inWeekly;
     private Date outWeekly;
     private Date inSaturday;
     private Date outSaturday;
     private Date inSunday;
     private Date outSunday;
     private Double dailyCost;
     private Double monthlyCost;
     private Set<Placetype> placetypes = new HashSet<Placetype>(0);
     private Set<Placeservices> placeserviceses = new HashSet<Placeservices>(0);
     
     private Set<Autorization> autorizations = new HashSet<Autorization>(0);

    public Place() {
    }

    public Place(String placeName, String placeAddress, String placePhone, String placePhoneAlt, Date placeCreated, Integer placeStatus, Integer placeOwner, Integer placeIsVzone, Set<Autorization> autorizations) {
       this.placeName = placeName;
       this.placeAddress = placeAddress;
       this.placePhone = placePhone;
       this.placePhoneAlt = placePhoneAlt;
       this.placeCreated = placeCreated;
       this.placeStatus = placeStatus;
       this.placeOwner = placeOwner;
       this.placeIsVzone = placeIsVzone;
       this.autorizations = autorizations;
    }
   
    public Integer getIdPlace() {
        return this.idPlace;
    }
    
    public void setIdPlace(Integer idPlace) {
        this.idPlace = idPlace;
    }
    public String getPlaceName() {
        return this.placeName;
    }
    
    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }
    public String getPlaceAddress() {
        return this.placeAddress;
    }
    
    public void setPlaceAddress(String placeAddress) {
        this.placeAddress = placeAddress;
    }
    public String getPlacePhone() {
        return this.placePhone;
    }
    
    public void setPlacePhone(String placePhone) {
        this.placePhone = placePhone;
    }
    public String getPlacePhoneAlt() {
        return this.placePhoneAlt;
    }
    
    public void setPlacePhoneAlt(String placePhoneAlt) {
        this.placePhoneAlt = placePhoneAlt;
    }
    public Date getPlaceCreated() {
        return this.placeCreated;
    }
    
    public void setPlaceCreated(Date placeCreated) {
        this.placeCreated = placeCreated;
    }
    public Integer getPlaceStatus() {
        return this.placeStatus;
    }
    
    public void setPlaceStatus(Integer placeStatus) {
        this.placeStatus = placeStatus;
    }
    public Integer getPlaceOwner() {
        return this.placeOwner;
    }
    
    public void setPlaceOwner(Integer placeOwner) {
        this.placeOwner = placeOwner;
    }
    public Integer getPlaceIsVzone() {
        return this.placeIsVzone;
    }
    
    public void setPlaceIsVzone(Integer placeIsVzone) {
        this.placeIsVzone = placeIsVzone;
    }
    public Set<Autorization> getAutorizations() {
        return this.autorizations;
    }
    
    public void setAutorizations(Set<Autorization> autorizations) {
        this.autorizations = autorizations;
    }

	public Integer getAccountID() {
		return accountID;
	}

	public void setAccountID(Integer accountID) {
		this.accountID = accountID;
	}

	public String getFiscalID() {
		return fiscalID;
	}

	public void setFiscalID(String fiscalID) {
		this.fiscalID = fiscalID;
	}

	public Integer getCountry() {
		return country;
	}

	public void setCountry(Integer country) {
		this.country = country;
	}

	public Integer getProvince() {
		return province;
	}

	public void setProvince(Integer province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getOwner_name() {
		return owner_name;
	}

	public void setOwner_name(String owner_name) {
		this.owner_name = owner_name;
	}

	public Set<Placetype> getPlacetypes() {
        return this.placetypes;
    }
    
    public void setPlacetypes(Set<Placetype> placetypes) {
        this.placetypes = placetypes;
    }
    public Set<Placeservices> getPlaceserviceses() {
        return this.placeserviceses;
    }
    
    public void setPlaceserviceses(Set<Placeservices> placeserviceses) {
        this.placeserviceses = placeserviceses;
    }

	public String getFacebook() {
		return facebook;
	}

	public void setFacebook(String facebook) {
		this.facebook = facebook;
	}

	public String getInstagram() {
		return instagram;
	}

	public void setInstagram(String instagram) {
		this.instagram = instagram;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Date getInWeekly() {
		return inWeekly;
	}

	public void setInWeekly(Date inWeekly) {
		this.inWeekly = inWeekly;
	}

	public Date getOutWeekly() {
		return outWeekly;
	}

	public void setOutWeekly(Date outWeekly) {
		this.outWeekly = outWeekly;
	}

	public Date getInSatuday() {
		return inSaturday;
	}

	public void setInSatuday(Date inSatuday) {
		this.inSaturday = inSatuday;
	}

	public Date getOutSaturday() {
		return outSaturday;
	}

	public void setOutSaturday(Date outSaturday) {
		this.outSaturday = outSaturday;
	}

	public Date getInSunday() {
		return inSunday;
	}

	public void setInSunday(Date inSunday) {
		this.inSunday = inSunday;
	}

	public Date getOutSunday() {
		return outSunday;
	}

	public void setOutSunday(Date outSunday) {
		this.outSunday = outSunday;
	}

	public Double getDailyCost() {
		return dailyCost;
	}

	public void setDailyCost(Double dailyCost) {
		this.dailyCost = dailyCost;
	}

	public Double getMonthlyCost() {
		return monthlyCost;
	}

	public void setMonthlyCost(Double monthlyCost) {
		this.monthlyCost = monthlyCost;
	}

	public Date getInSaturday() {
		return inSaturday;
	}

	public void setInSaturday(Date inSaturday) {
		this.inSaturday = inSaturday;
	}
	
	
    
}


