package com.liderbs.modelo;
// Generated 07-abr-2017 10:59:26 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Integer idprofile;
     private String profileName;
     private String profileDescription;
     private Date profileCreated;
     private String profileUserCreated;
     private Set<Account> accounts = new HashSet<Account>(0);
     private Set<Options> optionses = new HashSet<Options>(0);

    public Profile() {
    }

    public Profile(String profileName, String profileDescription, Date profileCreated, String profileUserCreated, Set<Account> accounts, Set<Options> optionses) {
       this.profileName = profileName;
       this.profileDescription = profileDescription;
       this.profileCreated = profileCreated;
       this.profileUserCreated = profileUserCreated;
       this.accounts = accounts;
       this.optionses = optionses;
    }
   
    public Integer getIdprofile() {
        return this.idprofile;
    }
    
    public void setIdprofile(Integer idprofile) {
        this.idprofile = idprofile;
    }
    public String getProfileName() {
        return this.profileName;
    }
    
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }
    public String getProfileDescription() {
        return this.profileDescription;
    }
    
    public void setProfileDescription(String profileDescription) {
        this.profileDescription = profileDescription;
    }
    public Date getProfileCreated() {
        return this.profileCreated;
    }
    
    public void setProfileCreated(Date profileCreated) {
        this.profileCreated = profileCreated;
    }
    public String getProfileUserCreated() {
        return this.profileUserCreated;
    }
    
    public void setProfileUserCreated(String profileUserCreated) {
        this.profileUserCreated = profileUserCreated;
    }
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }
    public Set<Options> getOptionses() {
        return this.optionses;
    }
    
    public void setOptionses(Set<Options> optionses) {
        this.optionses = optionses;
    }




}


