package com.liderbs.modelo;
// Generated 27-sep-2017 22:04:37 by Hibernate Tools 4.0.0



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer idreservation;
     private String reservationHolderName;
     private String reservationHolderId;
     private String reservationHolderTel;
     private String reservationHolderEmail;
     private String reservationHolderCode;
     private Integer reservationStatus;
     private Integer reservationIdclass;

    public Reservation() {
    }

    public Reservation(String reservationHolderName, String reservationHolderId, String reservationHolderTel, String reservationHolderEmail, String reservationHolderCode, Integer reservationStatus, Integer reservationIdclass) {
       this.reservationHolderName = reservationHolderName;
       this.reservationHolderId = reservationHolderId;
       this.reservationHolderTel = reservationHolderTel;
       this.reservationHolderEmail = reservationHolderEmail;
       this.reservationHolderCode = reservationHolderCode;
       this.reservationStatus = reservationStatus;
       this.reservationIdclass = reservationIdclass;
    }
   
    public Integer getIdreservation() {
        return this.idreservation;
    }
    
    public void setIdreservation(Integer idreservation) {
        this.idreservation = idreservation;
    }
    public String getReservationHolderName() {
        return this.reservationHolderName;
    }
    
    public void setReservationHolderName(String reservationHolderName) {
        this.reservationHolderName = reservationHolderName;
    }
    public String getReservationHolderId() {
        return this.reservationHolderId;
    }
    
    public void setReservationHolderId(String reservationHolderId) {
        this.reservationHolderId = reservationHolderId;
    }
    public String getReservationHolderTel() {
        return this.reservationHolderTel;
    }
    
    public void setReservationHolderTel(String reservationHolderTel) {
        this.reservationHolderTel = reservationHolderTel;
    }
    public String getReservationHolderEmail() {
        return this.reservationHolderEmail;
    }
    
    public void setReservationHolderEmail(String reservationHolderEmail) {
        this.reservationHolderEmail = reservationHolderEmail;
    }
    public String getReservationHolderCode() {
        return this.reservationHolderCode;
    }
    
    public void setReservationHolderCode(String reservationHolderCode) {
        this.reservationHolderCode = reservationHolderCode;
    }
    public Integer getReservationStatus() {
        return this.reservationStatus;
    }
    
    public void setReservationStatus(Integer reservationStatus) {
        this.reservationStatus = reservationStatus;
    }
    public Integer getReservationIdclass() {
        return this.reservationIdclass;
    }
    
    public void setReservationIdclass(Integer reservationIdclass) {
        this.reservationIdclass = reservationIdclass;
    }




}


