package com.liderbs.modelo;
// Generated 02-jun-2017 18:37:36 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Integer idschedule;
     private Day day;
     private Users users;
     private Date starttime;
     private Date endtime;

    public Schedule() {
    }

	
    public Schedule(Day day, Users users) {
        this.day = day;
        this.users = users;
    }
    public Schedule(Day day, Users users, Date starttime, Date endtime) {
       this.day = day;
       this.users = users;
       this.starttime = starttime;
       this.endtime = endtime;
    }
   
    public Integer getIdschedule() {
        return this.idschedule;
    }
    
    public void setIdschedule(Integer idschedule) {
        this.idschedule = idschedule;
    }
    public Day getDay() {
        return this.day;
    }
    
    public void setDay(Day day) {
        this.day = day;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }




}


