package com.liderbs.modelo;
// Generated 13-jun-2017 17:32:48 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Timetable generated by hbm2java
 */
public class Timetable  implements java.io.Serializable {


     private Integer idtimetable;
     private Day day;
     private Users users;
     private Date dateCreated;
     private Date timeStart;
     private Date timeEnd;

    public Timetable() {
    }

	
    public Timetable(Day day, Users users) {
        this.day = day;
        this.users = users;
    }
    public Timetable(Day day, Users users, Date dateCreated, Date timeStart, Date timeEnd) {
       this.day = day;
       this.users = users;
       this.dateCreated = dateCreated;
       this.timeStart = timeStart;
       this.timeEnd = timeEnd;
    }
   
    public Integer getIdtimetable() {
        return this.idtimetable;
    }
    
    public void setIdtimetable(Integer idtimetable) {
        this.idtimetable = idtimetable;
    }
    public Day getDay() {
        return this.day;
    }
    
    public void setDay(Day day) {
        this.day = day;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getTimeStart() {
        return this.timeStart;
    }
    
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }
    public Date getTimeEnd() {
        return this.timeEnd;
    }
    
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }




}


