package com.liderbs.modelo;
// Generated 26-abr-2017 15:46:42 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Trainer generated by hbm2java
 */
public class Trainer  implements java.io.Serializable {

	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idtrainer;
     private Academiclevel academiclevel;
     private Identification identification;
     private String name;
     private String lastname;
     private String lugar_nacimiento;
     private Date borndate;
     private Integer country;
     private Integer region;
     private String city;
     private String address;
     private String trainerAcknowledgement;
     private String academicArea;
     private String resumefile;
     private Integer usersIdusers;
     private Set<Experience> experiences = new HashSet<Experience>(0);
     private Set<Courses> courseses = new HashSet<Courses>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);

    public Trainer() {
    }

	
    public Trainer(Academiclevel academiclevel, Identification identification, Integer usersIdusers) {
        this.academiclevel = academiclevel;
        this.identification = identification;
        this.usersIdusers = usersIdusers;
    }
    public Trainer( Academiclevel academiclevel, Identification identification, String name, String lastname, String lugar_nacimiento, Date borndate, Integer country, Integer region, String city, String address, String trainerAcknowledgement, String academicArea, String resumefile, Integer usersIdusers, Set<Experience> experiences, Set<Courses> courseses) {
       this.academiclevel = academiclevel;
       this.identification = identification;
       this.name = name;
       this.lastname = lastname;
       this.lugar_nacimiento = lugar_nacimiento;
       this.borndate = borndate;
       this.country = country;
       this.region = region;
       this.city = city;
       this.address = address;
       this.trainerAcknowledgement = trainerAcknowledgement;
       this.academicArea = academicArea;
       this.resumefile = resumefile;
       this.usersIdusers = usersIdusers;
       this.experiences = experiences;
       this.courseses = courseses;
    }
   
    public Integer getIdtrainer() {
        return this.idtrainer;
    }
    
    public void setIdtrainer(Integer idtrainer) {
        this.idtrainer = idtrainer;
    }
    
    public Academiclevel getAcademiclevel() {
        return this.academiclevel;
    }
    
    public void setAcademiclevel(Academiclevel academiclevel) {
        this.academiclevel = academiclevel;
    }
    public Identification getIdentification() {
        return this.identification;
    }
    
    public void setIdentification(Identification identification) {
        this.identification = identification;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
      
    public String getLugar_nacimiento() {
		return lugar_nacimiento;
	}

	public void setLugar_nacimiento(String lugar_nacimiento) {
		this.lugar_nacimiento = lugar_nacimiento;
	}


	public void setBorndate(Date borndate) {
        this.borndate = borndate;
    }
    public Integer getCountry() {
        return this.country;
    }
    
    public void setCountry(Integer country) {
        this.country = country;
    }
    public Integer getRegion() {
        return this.region;
    }
    
    public void setRegion(Integer region) {
        this.region = region;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTrainerAcknowledgement() {
        return this.trainerAcknowledgement;
    }
    
    public void setTrainerAcknowledgement(String trainerAcknowledgement) {
        this.trainerAcknowledgement = trainerAcknowledgement;
    }
    public String getAcademicArea() {
        return this.academicArea;
    }
    
    public void setAcademicArea(String academicArea) {
        this.academicArea = academicArea;
    }
    public String getResumefile() {
        return this.resumefile;
    }
    
    public void setResumefile(String resumefile) {
        this.resumefile = resumefile;
    }
    public Integer getUsersIdusers() {
        return this.usersIdusers;
    }
    
    public void setUsersIdusers(Integer usersIdusers) {
        this.usersIdusers = usersIdusers;
    }
    public Set<Experience> getExperiences() {
        return this.experiences;
    }
    
    public void setExperiences(Set<Experience> experiences) {
        this.experiences = experiences;
    }
    public Set<Courses> getCourseses() {
        return this.courseses;
    }
    
    public void setCourseses(Set<Courses> courseses) {
        this.courseses = courseses;
    }


	public Date getBorndate() {
		return borndate;
	}

	public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }


}


