package com.liderbs.modelo;
// Generated 05-abr-2017 20:45:37 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long id;
     private Profile profile;
     private String username;
     private String password;
     private String name;
     private String lastname;
     private String userid;
     private String fixedphone;
     private String cellphone;
     private Date created;
     private Date lastlogin;
     private Integer status;
     private Float saldo;

    public Users() {
    }

	
    public Users(Long id, Profile profile) {
        this.id = id;
        this.profile = profile;
    }
    public Users(Long id, Profile profile, String username, String password, String name, String lastname, String userid, String fixedphone, String cellphone, Date created, Date lastlogin, Integer status, Float saldo) {
       this.id = id;
       this.profile = profile;
       this.username = username;
       this.password = password;
       this.name = name;
       this.lastname = lastname;
       this.userid = userid;
       this.fixedphone = fixedphone;
       this.cellphone = cellphone;
       this.created = created;
       this.lastlogin = lastlogin;
       this.status = status;
       this.saldo = saldo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getFixedphone() {
        return this.fixedphone;
    }
    
    public void setFixedphone(String fixedphone) {
        this.fixedphone = fixedphone;
    }
    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Float getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Float saldo) {
        this.saldo = saldo;
    }




}


