package com.liderbs.modelo;
// Generated 07-abr-2017 10:59:26 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {

	 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
     private Integer idusers;
     private String username;
     private String password;
     private String name;
     private String email;
     private String userid;
     private String fixedphone;
     private String cellphone;
     private Date created;
     private Date lastlogin;
     private Integer status;
     private Float saldo;
     private Integer istrainer;
     private String foto;
     private Set<Account> accounts = new HashSet<Account>(0);
     private Set<Category> categories = new HashSet<Category>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<Timetable> timetables = new HashSet<Timetable>(0);

    public Users() {
    }

    public Users(String username, String password, String name, String email, String userid, String fixedphone, String cellphone, Date created, Date lastlogin, Integer status, Float saldo, Set<Account> accounts) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.email = email;
       this.userid = userid;
       this.fixedphone = fixedphone;
       this.cellphone = cellphone;
       this.created = created;
       this.lastlogin = lastlogin;
       this.status = status;
       this.saldo = saldo;
       this.accounts = accounts;
    }
   
    public Integer getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(Integer idusers) {
        this.idusers = idusers;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getFixedphone() {
        return this.fixedphone;
    }
    
    public void setFixedphone(String fixedphone) {
        this.fixedphone = fixedphone;
    }
    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Float getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Float saldo) {
        this.saldo = saldo;
    }
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getIstrainer() {
		return istrainer;
	}

	public void setIstrainer(Integer istrainer) {
		this.istrainer = istrainer;
	}
	
	 public Set<Category> getCategories() {
	        return this.categories;
	 }
	    
	 public void setCategories(Set<Category> categories) {
	    this.categories = categories;
	 }

	public String getFoto() {
		return foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}
	 
	public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }
    

}


