package com.liderbs.modelo;
// Generated 16-may-2017 16:24:06 by Hibernate Tools 4.0.0



/**
 * UsuariosCategorias generated by hbm2java
 */
public class UsuariosCategorias  implements java.io.Serializable {


     private Integer idusuariosCategorias;
     private Category category;
     private Integer usuario;

    public UsuariosCategorias() {
    }

	
    public UsuariosCategorias(Category category) {
        this.category = category;
    }
    public UsuariosCategorias(Category category, Integer usuario) {
       this.category = category;
       this.usuario = usuario;
    }
   
    public Integer getIdusuariosCategorias() {
        return this.idusuariosCategorias;
    }
    
    public void setIdusuariosCategorias(Integer idusuariosCategorias) {
        this.idusuariosCategorias = idusuariosCategorias;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }




}


